export const categories = [
  { id: "all", label: "All Archives", icon: "Database" },
  { id: "trending", label: "Trending Now", icon: "Zap" },
  { id: "top-rated", label: "Highest Rated", icon: "Star" },
  { id: "new", label: "Newly Synced", icon: "Clock" },
];

export const filterSections = [
  {
    id: "format",
    title: "Format",
    options: [
      { id: "tv", label: "TV Series" },
      { id: "movie", label: "Movie" },
      { id: "ova", label: "OVA" },
    ],
  },
  {
    id: "status",
    title: "Air Status",
    options: [
      { id: "finished", label: "Completed" },
      { id: "airing", label: "Currently Airing" },
    ],
  },
  {
    id: "genres",
    title: "Neural Tags",
    options: [
      { id: "action",          label: "Action"          },
      { id: "adventure",       label: "Adventure"       },
      { id: "comedy",          label: "Comedy"          },
      { id: "drama",           label: "Drama"           },
      { id: "ecchi",           label: "Ecchi"           },
      { id: "fantasy",         label: "Fantasy"         },
      { id: "horror",          label: "Horror"          },
      { id: "mahou-shoujo",    label: "Mahou Shoujo"    },
      { id: "mecha",           label: "Mecha"           },
      { id: "music",           label: "Music"           },
      { id: "mystery",         label: "Mystery"         },
      { id: "psychological",   label: "Psychological"   },
      { id: "romance",         label: "Romance"         },
      { id: "sci-fi",          label: "Sci-Fi"          },
      { id: "slice-of-life",   label: "Slice of Life"   },
      { id: "sports",          label: "Sports"          },
      { id: "supernatural",    label: "Supernatural"    },
      { id: "suspense",        label: "Suspense"        },
      { id: "thriller",        label: "Thriller"        },
      { id: "isekai",          label: "Isekai"          },
      { id: "iyashikei",       label: "Iyashikei"       },
      { id: "harem",           label: "Harem"           },
      { id: "historical",      label: "Historical"      },
      { id: "school",          label: "School"          },
      { id: "military",        label: "Military"        },
      { id: "martial-arts",    label: "Martial Arts"    },
      { id: "parody",          label: "Parody"          },
      { id: "demons",          label: "Demons"          },
      { id: "vampire",         label: "Vampire"         },
      { id: "samurai",         label: "Samurai"         },
      { id: "space",           label: "Space"           },
      { id: "super-power",     label: "Super Power"     },
      { id: "shonen",          label: "Shonen"          },
      { id: "shojo",           label: "Shojo"           },
      { id: "seinen",          label: "Seinen"          },
      { id: "josei",           label: "Josei"           },
      { id: "kids",            label: "Kids"            },
      { id: "award-winning",   label: "Award Winning"   },
      { id: "gourmet",         label: "Gourmet"         },
      { id: "girls-love",      label: "Girls Love"      },
      { id: "boys-love",       label: "Boys Love"       },
    ],
  },
];